Massively improve code and reformat
MaskDuck/nextcord-ext-activities pull request #1
Opened 2022-03-15 16:33 UTC by Soheab

This PR improves the code and formatted with black --line-length 120.

2022-03-15 17:04 UTC, DenverCoder1 requested changes

2022-03-15 17:04 UTC, DenverCoder1 commented on nextcord/ext/activities/__init__.py
> +    unique: bool = True,
Maybe these should be documented?

2022-03-15 17:04 UTC, DenverCoder1 commented on nextcord/ext/activities/enums.py
> +        return self.value
```suggestion
        return self.value or 0
```

2022-03-15 17:04 UTC, DenverCoder1 commented on nextcord/ext/activities/enums.py
> +        return False
Probably better not to hard-code boost-locked status. Discord can change it rapidly and I believe they are even alpha-beta testing it differently in different servers.

2022-03-15 19:35 UTC, Soheab commented on nextcord/ext/activities/enums.py
> +        return False
Ah, I thought it would be better for the user to know but I guess it's better to leave it if it's unreliable.

2022-03-15 21:14 UTC, DenverCoder1 commented on examples/simple_activity_code_creation.py
> -bot.run('token here')
This entire example deleted?

2022-03-15 21:34 UTC, Soheab commented on examples/simple_activity_code_creation.py
> -bot.run('token here')
Yeah, it's exactly like the one in the [README Quick Example](https://github.com/MaskDuck/nextcord-ext-activities#quick-example)

2022-03-15 21:43 UTC, DenverCoder1 commented on examples/simple_activity_code_creation.py
> -bot.run('token here')
Ok, that makes sense.

It can't really hurt to have a basic example in the examples directory though.

Maybe the README could have an even quicker example (eg. without the bot variable initialization stuff) and have the complete bot code in the examples?

2022-03-16 00:48 UTC, MaskDuck commented
kinda cool tbh, but the problem in the docs is i dont really know how can we do autoclass =(

2022-03-16 02:05 UTC, DenverCoder1 commented on README.md
> +    await ctx.send(invite_link)
@MaskDuck First of all, that is an examples fix, not a breaking change. Second, I'd recommend putting it the way Sohaeb did since it makes more sense to print an invite URL to user, rather than the Invite object that the function returns.

2022-03-16 02:13 UTC, DenverCoder1 commented
> kinda cool tbh, but the problem in the docs is i dont really know how can we do autoclass =(

What I do for enums is

```
.. autoenum:: Alignment
    :members:
```

Using the package `enum-tools` as a docs requirement and `enum_tools.autoenum` added as an extension in `conf.py`.

(Example of a repo that uses this: [table2ascii](https://github.com/DenverCoder1/table2ascii))

2022-03-16 02:27 UTC, MaskDuck commented
@DenverCoder1 ok!

2022-03-16 02:32 UTC, MaskDuck commented
cool, reverted the change.

2022-03-16 02:32 UTC, MaskDuck approved these changes
gud

2022-03-16 02:32 UTC, DenverCoder1 commented
> ok (but id recommend if we can return the url directly since most user print the invite code and also the official example since it works)

It's better if it returns the Invite, since then it is more flexible as you can do other things as well such as check the number of uses, and revoke the invite with invite.delete.

In any case `str(invite)` will return the url of the Invite anyway, so there's basically no harm in doing so.

2022-03-16 02:33 UTC, MaskDuck commented
thanks!

2022-03-16 02:45 UTC, DenverCoder1 approved these changes
👍

2022-03-16 02:46 UTC, merged

2022-03-16 02:50 UTC, MaskDuck commented
would be included in the next major releases